services:
  app:
    image: ${DOCKER_REGISTRY-}portfolio:${TAG-latest} # Replace with your Docker image name
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Maps port 8080 on host to 8080 in container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:portfolio
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  db:
    image: h2database/h2:latest # Optional: If you want a standalone H2 instance
    ports:
      - "9092:9092" # H2 server port
    environment:
      - H2_OPTIONS=-ifNotExists